dist: xenial
sudo: required
language: minimal

git:
  quiet: true

services:
- docker

script:
- docker run -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:14.04 bash -x -e /v/.travis/python.release.sh
- ls -la dist/*.whl
- docker run -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:18.04 bash -x -e /v/.travis/install.test.sh

notifications:
- email: false
