dist: xenial
sudo: required
language: minimal

git:
  quiet: true

services:
- docker

addons:
  apt:
    update: true
    packages:
    - python3-pip

install:
- pip3 install -q twine
- twine --version

before_script:
- bash -x -e tests/test_ignite/start_ignite.sh
- bash -x -e tests/test_kafka/kafka_test.sh start kafka
- bash -x -e tests/test_kinesis/kinesis_test.sh start kinesis

stages:
- build
- preview
- install

jobs:
  include:
  - stage: build
    name: "Ubuntu 16.04 Build"
    script:
    - |
      set -e
      export TENSORFLOW_INSTALL="tensorflow==1.13.0rc2"
      docker run -e TENSORFLOW_INSTALL=${TENSORFLOW_INSTALL} -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:16.04 bash -x -e /v/.travis/build.test.sh
  - stage: build
    name: "Ubuntu 18.04 Build"
    script:
    - |
      set -e
      export TENSORFLOW_INSTALL="tensorflow==1.13.0rc2"
      docker run -e TENSORFLOW_INSTALL=${TENSORFLOW_INSTALL} -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:18.04 bash -x -e /v/.travis/build.test.sh
  - stage: preview
    name: "TensorFlow 2.0 Build"
    script:
    - |
      set -e
      export TENSORFLOW_INSTALL="tf-nightly-2.0-preview"
      docker run -e TENSORFLOW_INSTALL=${TENSORFLOW_INSTALL} -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:18.04 bash -x -e /v/.travis/build.test.sh
  - stage: install
    name: "Python, R, Nightly"
    script:
    - |
      set -e
      export TENSORFLOW_INSTALL="tensorflow==1.13.0rc2"
      docker run -e TENSORFLOW_INSTALL=${TENSORFLOW_INSTALL} -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:14.04 bash -x -e /v/.travis/python.release.sh --nightly ${TRAVIS_BUILD_NUMBER}
      ls -la wheelhouse/*.whl
      docker run -e TENSORFLOW_INSTALL=${TENSORFLOW_INSTALL} -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:16.04 bash -x -e /v/.travis/install.test.sh
      docker run -e TENSORFLOW_INSTALL=${TENSORFLOW_INSTALL} -i -t --rm -v $PWD:/v -w /v  --net=host ubuntu:18.04 bash -x -e /v/.travis/install.test.sh
      if [[ ( ${TRAVIS_BRANCH} == "master" ) && ( ${TRAVIS_EVENT_TYPE} != "pull_request" ) ]]; then
        ls wheelhouse/*.whl
        twine upload wheelhouse/*.whl
      fi

notifications:
- email: false
