dist: trusty
sudo: required

env:
  - BAZEL_OS=linux
    BAZEL_VERSION=0.17.2

services:
  - docker

before_script:
  - bash -x ${TRAVIS_BUILD_DIR}/tensorflow_io/kafka/python/kernel_tests/kafka_test.sh start kafka
  - bash -x ${TRAVIS_BUILD_DIR}/tensorflow_io/ignite/python/tests/start_ignite.sh

matrix:
  include:
    # - language: python
    #   python:
    #     - 2.7
    #   before_install:
    #     - bash -x ${TRAVIS_BUILD_DIR}/.travis/python.configure.sh
    #     - pip install pyarrow==0.11.1
    #   script:
    #     - bazel test --show_progress=no -s --verbose_failures --test_output=errors -- //tensorflow_io/...
    # - language: python
    #   python:
    #     - 3.4
    #   before_install:
    #     - bash -x ${TRAVIS_BUILD_DIR}/.travis/python.configure.sh
    #   script:
    #     - bazel test --show_progress=no -s --verbose_failures --test_output=errors -- //tensorflow_io/...
    # - language: python
    #   python:
    #     - 3.5
    #   before_install:
    #     - bash -x ${TRAVIS_BUILD_DIR}/.travis/python.configure.sh
    #     - pip install pyarrow==0.11.1
    #   script:
    #     - bazel test --show_progress=no -s --verbose_failures --test_output=errors -- //tensorflow_io/...
    # - language: python
    #   python:
    #     - 3.6
    #   before_install:
    #     - bash -x ${TRAVIS_BUILD_DIR}/.travis/python.configure.sh
    #     - pip install pyarrow==0.11.1
    #   script:
    #     - bazel test --show_progress=no -s --verbose_failures --test_output=errors -- //tensorflow_io/...
    - language: r
      r:
        - 3.5
      before_install:
        - bash -x ${TRAVIS_BUILD_DIR}/.travis/python.configure.sh
        - pip install --upgrade --ignore-installed --user travis pyarrow==0.11.1
        - bazel build build_pip_pkg
        - bazel-bin/build_pip_pkg artifacts
        - pip install --user travis artifacts/tensorflow_io-*.whl
        - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile
        - cd R-package
      script:
        - R -e "devtools::test()"

notifications:
  email: false
